# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=100, verbose_name='Nombre de la mascota')),
                ('nombre_propietario', models.CharField(max_length=100, verbose_name='Nombre del propietario')),
                ('fecha_cita', models.DateField(auto_now_add=True, verbose_name='Fecha de la cita')),
            ],
        ),
    ]
